$axure.loadCurrentPage({
  "url":"资料检索.html",
  "generationDate":new Date(1395142299582.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"63b810b0fe0346f789b68924b249cfc0",
    "type":"Axure:Page",
    "name":"资料检索",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d57588cc94af4a0c8abf5fa526c5dbfb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":4},
            "size":{
              "width":790,
              "height":814},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7f61a21981ee4a569265287f3e2a9c5b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":4},
                "size":{
                  "width":790,
                  "height":814},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u0.png"}},
{
          "id":"dc944b5dee23412d858d32c4251b6442",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":90},
            "size":{
              "width":790,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1027eac473194270b94869cd4d51e48b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":90},
                "size":{
                  "width":790,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"4d1b3d974e3944bf82212a6871584bb7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"11px",
            "fontWeight":"200",
            "location":{
              "x":735,
              "y":15},
            "size":{
              "width":23,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4339586f6d7142f79342bc222adb9a02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"11px",
                "fontWeight":"200",
                "location":{
                  "x":735,
                  "y":15},
                "size":{
                  "width":23,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01a78aad11ad431abd5bc27152733fa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"11px",
            "fontWeight":"200",
            "location":{
              "x":763,
              "y":15},
            "size":{
              "width":23,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"94eb134ec85b4d06bddbb4e9ed6654fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"11px",
                "fontWeight":"200",
                "location":{
                  "x":763,
                  "y":15},
                "size":{
                  "width":23,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a9281987fded4ebeb673644e4b386fe4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":43,
              "y":28},
            "size":{
              "width":107,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2e4d1f45ed2f4867a9199c355a4e57fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":43,
                  "y":28},
                "size":{
                  "width":107,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81311c71892f49f19f0b4997e35159b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":98},
            "size":{
              "width":27,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"34b6c19cf55f404ba3ece205bf8db258",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":98},
                "size":{
                  "width":27,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e3a71f00a33f461793e8b77fc945b7dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":97},
            "size":{
              "width":55,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc328ac502444e239e471710be4cb2ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":97},
                "size":{
                  "width":55,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e292f608ce33414e8b0ee430c589b082",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":200,
              "y":98},
            "size":{
              "width":53,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2781a49055014519a8bcbd4f1158e6bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":200,
                  "y":98},
                "size":{
                  "width":53,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92ae87f4f87b44fa9341cb4ce588a46a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":277,
              "y":98},
            "size":{
              "width":53,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a1329bc916d4a75962197e6a06b16f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":277,
                  "y":98},
                "size":{
                  "width":53,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"637445377bfc4f30b465af6eac18487e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":357,
              "y":98},
            "size":{
              "width":40,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0aac1a337c864dbaa7e8e290862a58fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":357,
                  "y":98},
                "size":{
                  "width":40,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0785d3b50a6448eeaa10c73b895f40e3",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":342,
              "y":90.5},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"3b9783ddb1ee44769c928b0e47efa739",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":20,
              "y":192},
            "size":{
              "width":140,
              "height":390},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1decf9364e7b4541a2a2bfcc73c045a9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":20,
                  "y":192},
                "size":{
                  "width":140,
                  "height":390},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u23.png"}},
{
          "id":"aec83e3430784066a78fc0e266415882",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":190},
            "size":{
              "width":85,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ef4bc3c178d4c10b94482ab3c010e7f",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Arial'"}},
                "size":{
                  "width":85,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"21b281931e0f4334b9fad05e0c66b5cc",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "mouseOver":{
                        "fontName":"'Arial'"}},
                    "size":{
                      "width":85,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fe40ebfceb9b4b55a0dd4964ac501aff",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "mouseOver":{
                            "fontName":"'Arial'"}},
                        "size":{
                          "width":85,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"21e7925b9460453b9eae848c5b724395",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":2},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"0735e5fe14c342f9b2a5900e5b08aaf9",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":22,
                          "y":2},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "buttonShapeId":"21b281931e0f4334b9fad05e0c66b5cc"}]},
{
          "id":"dec45ba71eda49d59372cc8a233dd6da",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":204},
            "size":{
              "width":80,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a0c497fdf98450ea3b015909cd34895",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "size":{
                  "width":80,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"6b89ccb280494900ae240861072403a9",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "size":{
                      "width":80,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"01ada22553134000b8d24b90229a0acb",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Light', 'Heiti SC'",
                        "fontWeight":"200",
                        "size":{
                          "width":80,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"168b03de74ce4f259014a04298568c0c",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c33ea60bbd6f4f23a49c80e2c958d300",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"6121413c5ad04bd587e4aaa3c92a7546",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"c33ea60bbd6f4f23a49c80e2c958d300"},
{
                  "id":"cf5bec832f7146e08dbc66e889f96368",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"89c5272b572d4e0a9027f79707fb733c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/data/u33.png",
                    "selected~":"images/data/u33_selected.png"}},
{
                  "id":"e38ac34b63c4431999de4888c3bca409",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c8ead710e7714721add36e056a5389cf",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"4f36b077565c41b7af15162f85abb7e3",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"c8ead710e7714721add36e056a5389cf"},
{
                  "id":"ae75460c0f0145bca0ef3fcd61e06f50",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c801dd3035614a95b8b731d055931531",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"72660726acaf44df8b286fe64e0e1032",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"c801dd3035614a95b8b731d055931531"}],
              "buttonShapeId":"6b89ccb280494900ae240861072403a9"}]},
{
          "id":"621bb35c11fe4809ad697a8f832ee2be",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"28px",
            "fontWeight":"200",
            "location":{
              "x":180,
              "y":150},
            "size":{
              "width":85,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8b33040d113441d8f5d40127af77ae0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"28px",
                "fontWeight":"200",
                "location":{
                  "x":180,
                  "y":150},
                "size":{
                  "width":85,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7f09be1bb55348e1af1117bd74e22142",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":730},
            "size":{
              "width":790,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bceb264c024d4e01b67db3525b486c6d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":730},
                "size":{
                  "width":790,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u48.png"}},
{
          "id":"6ae20cea3321440fb6ac0f15ea5630fa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":773},
            "size":{
              "width":336,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fad4233e162f4101bf2cfadda12ea37c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":773},
                "size":{
                  "width":336,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fd53aa75de864b228958a3eb6b8a900f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033FF,
              "opacity":1},
            "location":{
              "x":23,
              "y":791},
            "size":{
              "width":316,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8270a9a942944358a5de487131b7741",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":791},
                "size":{
                  "width":316,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5531bc4520fe42979c7759ec20556cc2",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":166,
              "y":150},
            "size":{
              "width":10,
              "height":580},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/data/u55_line.png"}},
{
          "id":"f6dab4a1cc984aba965d2aaade45466f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":150},
            "size":{
              "width":140,
              "height":42},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"959c969f5b6745018b20b92037b521c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":150},
                "size":{
                  "width":140,
                  "height":42},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u56.png"}},
{
          "id":"2a822370022e4986a6d5bf87a77d142d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Medium', 'Heiti SC'",
            "fontWeight":"700",
            "location":{
              "x":41,
              "y":167},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f94168e2580847478d9cd2829beea333",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Medium', 'Heiti SC'",
                "fontWeight":"700",
                "location":{
                  "x":41,
                  "y":167},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11e67051cdff47df8620e2e6675b052f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":273,
              "y":156},
            "size":{
              "width":62,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a28b35daddda45899c89c2bfa0fa9a54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9,
                  "opacity":1},
                "location":{
                  "x":273,
                  "y":156},
                "size":{
                  "width":62,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"37b3afbf6c7a4ad1823bbab62ed3ef5e",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":234},
            "size":{
              "width":67,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ea218a3b4ab4f73bb193e24bddf3031",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "size":{
                  "width":67,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"a1a6383654a342ae94a53633f4c11a2c",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "fontName":"'Heiti SC Light', 'Heiti SC'",
                    "fontWeight":"200",
                    "size":{
                      "width":67,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"64370b4097994316a8c9f1022390b537",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontName":"'Heiti SC Light', 'Heiti SC'",
                        "fontWeight":"200",
                        "size":{
                          "width":67,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"4b56bfb76b1641988882f3b96bd091ca",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"dc26996a402a41aba6e5a3782d93a1b4",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"ec4cf9d2bd814059a50e89007df184bb",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"dc26996a402a41aba6e5a3782d93a1b4"},
{
                  "id":"40b787e9bc914ca382142d8c7f2d31b1",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fa86e8845cdc48e1a5cf79072b3eaffa",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/data/u33.png",
                    "selected~":"images/data/u33_selected.png"}},
{
                  "id":"40a53d2655874055a2a1ca4d991da649",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"eefd8653815748f8a1b536ac599127d4",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"163ede68b5fa43efb58d48c7fa8c84e2",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"eefd8653815748f8a1b536ac599127d4"},
{
                  "id":"6c6794bca09e4f93bfdc5979374bc0f2",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"2dcd805d4b7a466cad278d8985551f53",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"545896a1442349739359f206de33de56",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"2dcd805d4b7a466cad278d8985551f53"}],
              "buttonShapeId":"a1a6383654a342ae94a53633f4c11a2c"}]},
{
          "id":"ce2a17d8c5e6492a9544c79c13fed5d0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":185,
              "y":190},
            "size":{
              "width":40,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4ececa33bff429aa6e7608373dceca2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":185,
                  "y":190},
                "size":{
                  "width":40,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9ba534b596b3479f8229bfbe8e66ef07",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":207},
            "size":{
              "width":135,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"7c2d023cb2aa4944b518067ac676c407",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":357,
              "y":191},
            "size":{
              "width":66,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"018e5d17545f4c33b9490758fa2c807f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":357,
                  "y":191},
                "size":{
                  "width":66,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fa47869b2fc149208efef05271704927",
          "label":"",
          "type":"comboBox",
          "styleType":"comboBox",
          "visible":true,
          "style":{
            "location":{
              "x":357,
              "y":206},
            "size":{
              "width":135,
              "height":20}},
          "adaptiveStyles":{
}},
{
          "id":"d5c391dee69b4f13a2af883abbcd1a25",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":530,
              "y":202},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"81ea3fbf12894b69a5e87da7a1f4aba9",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":237},
            "size":{
              "width":601,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资料检索/u81_line.png"}},
{
          "id":"320d5c503a0848b1a84059a036535097",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":260},
            "size":{
              "width":601,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资料检索/u82_line.png"}},
{
          "id":"43a5c55c30f64031b5be4d1e3ad40dcc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":247},
            "size":{
              "width":168,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c096d2b7b814d70be14049931cbc448",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":187,
                  "y":247},
                "size":{
                  "width":168,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"750bd42f2c8441e4b300b490264d5ff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":355,
              "y":248},
            "size":{
              "width":51,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"028e237997e24cd2a0fb1f3d6f4a5fb9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":355,
                  "y":248},
                "size":{
                  "width":51,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0e27ccb3462643eeb0ef8c41211690da",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":285},
            "size":{
              "width":423,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资料检索/u87_line.png"}},
{
          "id":"5e2650e0caae4e79854676c46ab25677",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":620,
              "y":285},
            "size":{
              "width":60,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资料检索/u88_line.png"}},
{
          "id":"c6017ee2e9fc400ebb2b39027843b3cf",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":690,
              "y":285},
            "size":{
              "width":96,
              "height":10},
            "borderWidth":"2"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资料检索/u89_line.png"}},
{
          "id":"c2ca0ea49c254a6f847862d76c9f6898",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Medium', 'Heiti SC'",
            "fontWeight":"700",
            "location":{
              "x":187,
              "y":272},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d3ec06c4d8047b684064ae5053ffbfc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Medium', 'Heiti SC'",
                "fontWeight":"700",
                "location":{
                  "x":187,
                  "y":272},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"60a09ea55b5444479233b57c6787bbc9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Medium', 'Heiti SC'",
            "fontWeight":"700",
            "location":{
              "x":620,
              "y":272},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be8f1653b61f4066885d2cc1f40729e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Medium', 'Heiti SC'",
                "fontWeight":"700",
                "location":{
                  "x":620,
                  "y":272},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c25b73535b5c47e19a2e66be7088a260",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Medium', 'Heiti SC'",
            "fontWeight":"700",
            "location":{
              "x":690,
              "y":272},
            "size":{
              "width":27,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e1866c2141649feb2b652fb9da4028f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Medium', 'Heiti SC'",
                "fontWeight":"700",
                "location":{
                  "x":690,
                  "y":272},
                "size":{
                  "width":27,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5b4a65d3996407984a7a2ba69e95e86",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":339},
            "size":{
              "width":601,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资料检索/u82_line.png"}},
{
          "id":"f53692ca03c74a558b1c11a39b32ea20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":187,
              "y":297},
            "size":{
              "width":227,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3632fc140b674b4389b090221ed8580b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":187,
                  "y":297},
                "size":{
                  "width":227,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c3628976ae714c6ab671475b38ff4ed6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":186,
              "y":309},
            "size":{
              "width":291,
              "height":31},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b89eb5e4caa45fa9d5a1dcb3411b8f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":186,
                  "y":309},
                "size":{
                  "width":291,
                  "height":31},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u2.png"}},
{
          "id":"5f2013896dab4df192f50da2150a559e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":620,
              "y":297},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"056e5a218c184f2a98f89a767b3c31cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":620,
                  "y":297},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"70908a7a105f4c30bd08a7cc2af622f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":296},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3d58f85aa294b5e9f809b0dfb6fdfce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":296},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"10f6f264d3af4ed6bdf433ac8d952d84",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":396},
            "size":{
              "width":601,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资料检索/u82_line.png"}},
{
          "id":"c6c8b00a06964335a03c15825dbec9fd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":187,
              "y":354},
            "size":{
              "width":227,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bad7ef9002ae469cbd05fd362d6d6201",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":187,
                  "y":354},
                "size":{
                  "width":227,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"990058af5d4a418bb3a2a2e31a22a2d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":186,
              "y":366},
            "size":{
              "width":291,
              "height":31},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9383b1b0c3344d182e1b8934755c566",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":186,
                  "y":366},
                "size":{
                  "width":291,
                  "height":31},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u2.png"}},
{
          "id":"11387ef57bc6474d817e998cdad8e08b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":620,
              "y":354},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"178aa18ca23b48468cd929ff21cf433b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":620,
                  "y":354},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3c12e001aa14416890e85cedcb524af0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":691,
              "y":353},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1aea12217b70407db5daa9254fec40d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":691,
                  "y":353},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12e58f14ce1145e39f4bc36a6c85201c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":650},
            "size":{
              "width":601,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFBCBCBC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/资料检索/u82_line.png"}},
{
          "id":"8be72625b49843d4b5bd33b2d0867771",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":187,
              "y":664},
            "size":{
              "width":168,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0de7bbfcfab04d5086da458c27931e76",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":187,
                  "y":664},
                "size":{
                  "width":168,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c7492031c944e72bf829fce1a713a90",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":355,
              "y":665},
            "size":{
              "width":51,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61e39a0be21c47229397b3f6ddd056b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":355,
                  "y":665},
                "size":{
                  "width":51,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d57588cc94af4a0c8abf5fa526c5dbfb":{
      "scriptId":"u0"},
    "7f61a21981ee4a569265287f3e2a9c5b":{
      "scriptId":"u1"},
    "dc944b5dee23412d858d32c4251b6442":{
      "scriptId":"u2"},
    "1027eac473194270b94869cd4d51e48b":{
      "scriptId":"u3"},
    "4d1b3d974e3944bf82212a6871584bb7":{
      "scriptId":"u4"},
    "4339586f6d7142f79342bc222adb9a02":{
      "scriptId":"u5"},
    "01a78aad11ad431abd5bc27152733fa7":{
      "scriptId":"u6"},
    "94eb134ec85b4d06bddbb4e9ed6654fa":{
      "scriptId":"u7"},
    "a9281987fded4ebeb673644e4b386fe4":{
      "scriptId":"u8"},
    "2e4d1f45ed2f4867a9199c355a4e57fa":{
      "scriptId":"u9"},
    "81311c71892f49f19f0b4997e35159b6":{
      "scriptId":"u10"},
    "34b6c19cf55f404ba3ece205bf8db258":{
      "scriptId":"u11"},
    "e3a71f00a33f461793e8b77fc945b7dd":{
      "scriptId":"u12"},
    "bc328ac502444e239e471710be4cb2ff":{
      "scriptId":"u13"},
    "e292f608ce33414e8b0ee430c589b082":{
      "scriptId":"u14"},
    "2781a49055014519a8bcbd4f1158e6bb":{
      "scriptId":"u15"},
    "92ae87f4f87b44fa9341cb4ce588a46a":{
      "scriptId":"u16"},
    "5a1329bc916d4a75962197e6a06b16f1":{
      "scriptId":"u17"},
    "637445377bfc4f30b465af6eac18487e":{
      "scriptId":"u18"},
    "0aac1a337c864dbaa7e8e290862a58fd":{
      "scriptId":"u19"},
    "0785d3b50a6448eeaa10c73b895f40e3":{
      "scriptId":"u20"},
    "3b9783ddb1ee44769c928b0e47efa739":{
      "scriptId":"u21"},
    "1decf9364e7b4541a2a2bfcc73c045a9":{
      "scriptId":"u22"},
    "aec83e3430784066a78fc0e266415882":{
      "scriptId":"u23"},
    "3ef4bc3c178d4c10b94482ab3c010e7f":{
      "scriptId":"u24"},
    "21e7925b9460453b9eae848c5b724395":{
      "scriptId":"u25"},
    "0735e5fe14c342f9b2a5900e5b08aaf9":{
      "scriptId":"u26"},
    "21b281931e0f4334b9fad05e0c66b5cc":{
      "scriptId":"u27"},
    "fe40ebfceb9b4b55a0dd4964ac501aff":{
      "scriptId":"u28"},
    "dec45ba71eda49d59372cc8a233dd6da":{
      "scriptId":"u29"},
    "7a0c497fdf98450ea3b015909cd34895":{
      "scriptId":"u30"},
    "cf5bec832f7146e08dbc66e889f96368":{
      "scriptId":"u31"},
    "89c5272b572d4e0a9027f79707fb733c":{
      "scriptId":"u32"},
    "6b89ccb280494900ae240861072403a9":{
      "scriptId":"u33"},
    "01ada22553134000b8d24b90229a0acb":{
      "scriptId":"u34"},
    "168b03de74ce4f259014a04298568c0c":{
      "scriptId":"u35"},
    "c33ea60bbd6f4f23a49c80e2c958d300":{
      "scriptId":"u36"},
    "6121413c5ad04bd587e4aaa3c92a7546":{
      "scriptId":"u37"},
    "e38ac34b63c4431999de4888c3bca409":{
      "scriptId":"u38"},
    "c8ead710e7714721add36e056a5389cf":{
      "scriptId":"u39"},
    "4f36b077565c41b7af15162f85abb7e3":{
      "scriptId":"u40"},
    "ae75460c0f0145bca0ef3fcd61e06f50":{
      "scriptId":"u41"},
    "c801dd3035614a95b8b731d055931531":{
      "scriptId":"u42"},
    "72660726acaf44df8b286fe64e0e1032":{
      "scriptId":"u43"},
    "621bb35c11fe4809ad697a8f832ee2be":{
      "scriptId":"u44"},
    "a8b33040d113441d8f5d40127af77ae0":{
      "scriptId":"u45"},
    "7f09be1bb55348e1af1117bd74e22142":{
      "scriptId":"u46"},
    "bceb264c024d4e01b67db3525b486c6d":{
      "scriptId":"u47"},
    "6ae20cea3321440fb6ac0f15ea5630fa":{
      "scriptId":"u48"},
    "fad4233e162f4101bf2cfadda12ea37c":{
      "scriptId":"u49"},
    "fd53aa75de864b228958a3eb6b8a900f":{
      "scriptId":"u50"},
    "c8270a9a942944358a5de487131b7741":{
      "scriptId":"u51"},
    "5531bc4520fe42979c7759ec20556cc2":{
      "scriptId":"u52"},
    "f6dab4a1cc984aba965d2aaade45466f":{
      "scriptId":"u53"},
    "959c969f5b6745018b20b92037b521c8":{
      "scriptId":"u54"},
    "2a822370022e4986a6d5bf87a77d142d":{
      "scriptId":"u55"},
    "f94168e2580847478d9cd2829beea333":{
      "scriptId":"u56"},
    "11e67051cdff47df8620e2e6675b052f":{
      "scriptId":"u57"},
    "a28b35daddda45899c89c2bfa0fa9a54":{
      "scriptId":"u58"},
    "37b3afbf6c7a4ad1823bbab62ed3ef5e":{
      "scriptId":"u59"},
    "5ea218a3b4ab4f73bb193e24bddf3031":{
      "scriptId":"u60"},
    "40b787e9bc914ca382142d8c7f2d31b1":{
      "scriptId":"u61"},
    "fa86e8845cdc48e1a5cf79072b3eaffa":{
      "scriptId":"u62"},
    "a1a6383654a342ae94a53633f4c11a2c":{
      "scriptId":"u63"},
    "64370b4097994316a8c9f1022390b537":{
      "scriptId":"u64"},
    "4b56bfb76b1641988882f3b96bd091ca":{
      "scriptId":"u65"},
    "dc26996a402a41aba6e5a3782d93a1b4":{
      "scriptId":"u66"},
    "ec4cf9d2bd814059a50e89007df184bb":{
      "scriptId":"u67"},
    "40a53d2655874055a2a1ca4d991da649":{
      "scriptId":"u68"},
    "eefd8653815748f8a1b536ac599127d4":{
      "scriptId":"u69"},
    "163ede68b5fa43efb58d48c7fa8c84e2":{
      "scriptId":"u70"},
    "6c6794bca09e4f93bfdc5979374bc0f2":{
      "scriptId":"u71"},
    "2dcd805d4b7a466cad278d8985551f53":{
      "scriptId":"u72"},
    "545896a1442349739359f206de33de56":{
      "scriptId":"u73"},
    "ce2a17d8c5e6492a9544c79c13fed5d0":{
      "scriptId":"u74"},
    "d4ececa33bff429aa6e7608373dceca2":{
      "scriptId":"u75"},
    "9ba534b596b3479f8229bfbe8e66ef07":{
      "scriptId":"u76"},
    "7c2d023cb2aa4944b518067ac676c407":{
      "scriptId":"u77"},
    "018e5d17545f4c33b9490758fa2c807f":{
      "scriptId":"u78"},
    "fa47869b2fc149208efef05271704927":{
      "scriptId":"u79"},
    "d5c391dee69b4f13a2af883abbcd1a25":{
      "scriptId":"u80"},
    "81ea3fbf12894b69a5e87da7a1f4aba9":{
      "scriptId":"u81"},
    "320d5c503a0848b1a84059a036535097":{
      "scriptId":"u82"},
    "43a5c55c30f64031b5be4d1e3ad40dcc":{
      "scriptId":"u83"},
    "6c096d2b7b814d70be14049931cbc448":{
      "scriptId":"u84"},
    "750bd42f2c8441e4b300b490264d5ff7":{
      "scriptId":"u85"},
    "028e237997e24cd2a0fb1f3d6f4a5fb9":{
      "scriptId":"u86"},
    "0e27ccb3462643eeb0ef8c41211690da":{
      "scriptId":"u87"},
    "5e2650e0caae4e79854676c46ab25677":{
      "scriptId":"u88"},
    "c6017ee2e9fc400ebb2b39027843b3cf":{
      "scriptId":"u89"},
    "c2ca0ea49c254a6f847862d76c9f6898":{
      "scriptId":"u90"},
    "6d3ec06c4d8047b684064ae5053ffbfc":{
      "scriptId":"u91"},
    "60a09ea55b5444479233b57c6787bbc9":{
      "scriptId":"u92"},
    "be8f1653b61f4066885d2cc1f40729e2":{
      "scriptId":"u93"},
    "c25b73535b5c47e19a2e66be7088a260":{
      "scriptId":"u94"},
    "7e1866c2141649feb2b652fb9da4028f":{
      "scriptId":"u95"},
    "a5b4a65d3996407984a7a2ba69e95e86":{
      "scriptId":"u96"},
    "f53692ca03c74a558b1c11a39b32ea20":{
      "scriptId":"u97"},
    "3632fc140b674b4389b090221ed8580b":{
      "scriptId":"u98"},
    "c3628976ae714c6ab671475b38ff4ed6":{
      "scriptId":"u99"},
    "3b89eb5e4caa45fa9d5a1dcb3411b8f9":{
      "scriptId":"u100"},
    "5f2013896dab4df192f50da2150a559e":{
      "scriptId":"u101"},
    "056e5a218c184f2a98f89a767b3c31cf":{
      "scriptId":"u102"},
    "70908a7a105f4c30bd08a7cc2af622f0":{
      "scriptId":"u103"},
    "c3d58f85aa294b5e9f809b0dfb6fdfce":{
      "scriptId":"u104"},
    "10f6f264d3af4ed6bdf433ac8d952d84":{
      "scriptId":"u105"},
    "c6c8b00a06964335a03c15825dbec9fd":{
      "scriptId":"u106"},
    "bad7ef9002ae469cbd05fd362d6d6201":{
      "scriptId":"u107"},
    "990058af5d4a418bb3a2a2e31a22a2d1":{
      "scriptId":"u108"},
    "e9383b1b0c3344d182e1b8934755c566":{
      "scriptId":"u109"},
    "11387ef57bc6474d817e998cdad8e08b":{
      "scriptId":"u110"},
    "178aa18ca23b48468cd929ff21cf433b":{
      "scriptId":"u111"},
    "3c12e001aa14416890e85cedcb524af0":{
      "scriptId":"u112"},
    "1aea12217b70407db5daa9254fec40d7":{
      "scriptId":"u113"},
    "12e58f14ce1145e39f4bc36a6c85201c":{
      "scriptId":"u114"},
    "8be72625b49843d4b5bd33b2d0867771":{
      "scriptId":"u115"},
    "0de7bbfcfab04d5086da458c27931e76":{
      "scriptId":"u116"},
    "0c7492031c944e72bf829fce1a713a90":{
      "scriptId":"u117"},
    "61e39a0be21c47229397b3f6ddd056b0":{
      "scriptId":"u118"}}});