$axure.loadCurrentPage({
  "url":"news.html",
  "generationDate":new Date(1395142300155.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"411309689935490b89588e9478196f4a",
    "type":"Axure:Page",
    "name":"news",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b3c9a10d914b42c9984bba0666705c84",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":10},
            "size":{
              "width":790,
              "height":814},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cce1fd2bdd5a4d5cb87a65afbc9035fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":10},
                "size":{
                  "width":790,
                  "height":814},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u0.png"}},
{
          "id":"65f156d8000549a98ce69eb4687fca9e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":267,
              "y":252},
            "size":{
              "width":291,
              "height":31},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3095da263ad5475490cb17589ec6e6ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":267,
                  "y":252},
                "size":{
                  "width":291,
                  "height":31},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u2.png"}},
{
          "id":"33aeb46a84254423b22006fdf47d0d2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":90},
            "size":{
              "width":790,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5ff912f7387491ab2b9864abaa4870e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":90},
                "size":{
                  "width":790,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/home/u2.png"}},
{
          "id":"fd94fc126d1e45bd845d48e39077b2ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"11px",
            "fontWeight":"200",
            "location":{
              "x":735,
              "y":15},
            "size":{
              "width":23,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17aae3e87d7b4a5995ba3c02354c549c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"11px",
                "fontWeight":"200",
                "location":{
                  "x":735,
                  "y":15},
                "size":{
                  "width":23,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"934ba43265224f5a9ec9adf4a9cfaaaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"11px",
            "fontWeight":"200",
            "location":{
              "x":763,
              "y":15},
            "size":{
              "width":23,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"619a959c1cf14d6a928f45ad33bb49af",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"11px",
                "fontWeight":"200",
                "location":{
                  "x":763,
                  "y":15},
                "size":{
                  "width":23,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef5fb7bb5c5e4b52bc01a736a91459c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":43,
              "y":28},
            "size":{
              "width":107,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6513471d99cd4cc0899cefae7cafa482",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "location":{
                  "x":43,
                  "y":28},
                "size":{
                  "width":107,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"441de1f5b4da46478441b1b40a4b6e40",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":50,
              "y":98},
            "size":{
              "width":27,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fb50c224c5840c0b8e01ff8e1dd2e2d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":50,
                  "y":98},
                "size":{
                  "width":27,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e24ed4c2b1c34b009af632db32374d7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":115,
              "y":97},
            "size":{
              "width":55,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"014247a9283e410ea1d918aeadef7c5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":115,
                  "y":97},
                "size":{
                  "width":55,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"68e98ab38fb2409f9c56c4e819e47e41",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":200,
              "y":98},
            "size":{
              "width":53,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d93ca05f077b422b963accec2e5c87ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":200,
                  "y":98},
                "size":{
                  "width":53,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"baf530ac4ad84eaa9e276fe0b652631c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":277,
              "y":98},
            "size":{
              "width":53,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64f9351d97a349d893bc95f8131586e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":277,
                  "y":98},
                "size":{
                  "width":53,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5018abc3292f4eacaff60a3a5959f3e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":357,
              "y":98},
            "size":{
              "width":40,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"98a5d42254904453b87e68cec138336a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":357,
                  "y":98},
                "size":{
                  "width":40,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d6ef87978af14869adf628da8bd570e7",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":191.5,
              "y":90.5},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"058bb836951d4167ba56127c9dc8982a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFF9F9F9},
            "location":{
              "x":20,
              "y":192},
            "size":{
              "width":140,
              "height":390},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6c976049024246ff94aba834232d5954",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFF9F9F9},
                "location":{
                  "x":20,
                  "y":192},
                "size":{
                  "width":140,
                  "height":390},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u23.png"}},
{
          "id":"4a249a8f59224c3ca0448de0fe4a1e9b",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":840,
              "y":190},
            "size":{
              "width":85,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96d1a76fc861434583828145b99fb12f",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fontName":"'Arial'"}},
                "size":{
                  "width":85,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"5bb4ed51fbea4c5294e4802547ebd4e6",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "mouseOver":{
                        "fontName":"'Arial'"}},
                    "size":{
                      "width":85,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6bd60adaccbb4a2b8a581ab7f01ad00c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "mouseOver":{
                            "fontName":"'Arial'"}},
                        "size":{
                          "width":85,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif",
                    "mouseOver~":"resources/images/transparent.gif"}},
{
                  "id":"eb1ed36a7dd34f25937b902b5d3d95d6",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":22,
                      "y":2},
                    "size":{
                      "width":16,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b883eb5b4017425387460a4bdba67b40",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":22,
                          "y":2},
                        "size":{
                          "width":16,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}],
              "buttonShapeId":"5bb4ed51fbea4c5294e4802547ebd4e6"}]},
{
          "id":"349aecee344447f9b37f4ccf432009c3",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":204},
            "size":{
              "width":91,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71b738eaef444753bb4ea490fcfff660",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "size":{
                  "width":91,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ff2ad1ab7fe8408f8992be5269e2e6da",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":91,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9169b47aff924eb9a7edb56d89277bcb",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":91,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"f1544718c97245f3a3ddaae1caa42216",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c56e3f862a6d45a7aedfc74c2976f7fa",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"cf84650e84a946e08fd8885e88dee3a2",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"c56e3f862a6d45a7aedfc74c2976f7fa"},
{
                  "id":"ead7117a07df4246b2be4e035d387888",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"fc111f3f00504153aaad924bfb800f8c",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/data/u33.png",
                    "selected~":"images/data/u33_selected.png"}},
{
                  "id":"65558c793c5643a18e4328caf87d9cf2",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"550c9befc02248379045e016e9269739",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"bfa155ffaa514e6ead0719e5c3bbbc44",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"550c9befc02248379045e016e9269739"},
{
                  "id":"7db9b1c9f9b5472fbeee30343e5fbcf0",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bbca3ed6511145c7afb2e9876c5fbf7d",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"a97d79ab46a642acbe95dfa3c267b19d",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"bbca3ed6511145c7afb2e9876c5fbf7d"}],
              "buttonShapeId":"ff2ad1ab7fe8408f8992be5269e2e6da"}]},
{
          "id":"5ce4a9a3026a4455aada90d2a0e36fab",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":180,
              "y":150},
            "size":{
              "width":139,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f87c9ffa6c8143cbb60f883eec07a960",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":180,
                  "y":150},
                "size":{
                  "width":139,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9575aa3ef5cb41c680ab7097cedd6297",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":730},
            "size":{
              "width":790,
              "height":40},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF949494}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"451e9afc934e4fda97cba86ba3557ebb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":730},
                "size":{
                  "width":790,
                  "height":40},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF949494}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u48.png"}},
{
          "id":"c238e466333548069279d2cb9e181e89",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":22,
              "y":773},
            "size":{
              "width":336,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e742a48d67f47188fe7f0d6733dc673",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":22,
                  "y":773},
                "size":{
                  "width":336,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d7d2cd6bcba4f728159aea00ed148d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0033FF,
              "opacity":1},
            "location":{
              "x":23,
              "y":791},
            "size":{
              "width":316,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2936c58512e74bbebb9dc648d17c9c0d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0033FF,
                  "opacity":1},
                "location":{
                  "x":23,
                  "y":791},
                "size":{
                  "width":316,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9afb30d13a8e4b888ae645d4a22412dd",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":660,
              "y":120},
            "size":{
              "width":10,
              "height":610},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/data/u54_line.png"}},
{
          "id":"761362c8cc5f44468dada9fa654fe68a",
          "label":"",
          "type":"verticalLine",
          "styleType":"verticalLine",
          "visible":true,
          "style":{
            "location":{
              "x":166,
              "y":150},
            "size":{
              "width":10,
              "height":580},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/data/u55_line.png"}},
{
          "id":"63ecaea79c444ccc91de1b7dddfa676a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":20,
              "y":150},
            "size":{
              "width":140,
              "height":42},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d12b69e7b704426ab8199f855f3ff1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":20,
                  "y":150},
                "size":{
                  "width":140,
                  "height":42},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u56.png"}},
{
          "id":"ffb052063f134553afd30638bfc46b3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Medium', 'Heiti SC'",
            "fontWeight":"700",
            "location":{
              "x":41,
              "y":167},
            "size":{
              "width":66,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ce680f519fc4a74a264c187aeb4e3ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Medium', 'Heiti SC'",
                "fontWeight":"700",
                "location":{
                  "x":41,
                  "y":167},
                "size":{
                  "width":66,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"80625e432e8f46009c06da32bef3c45b",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":667,
              "y":150},
            "size":{
              "width":142,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/data/u60_line.png"}},
{
          "id":"886c9cd9284f43c4a07bb6918e33e1b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Bold', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":670,
              "y":165},
            "size":{
              "width":129,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f8462fd52664d1eaa5d042544a24ce3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Bold', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":670,
                  "y":165},
                "size":{
                  "width":129,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a1ac012e7934734955b02afa5b7417d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":190},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"588422fa02b54feca85e41e2262de3ed",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":190},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"da277a58fcae4372a3cd2a158cb33f96",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"11px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":754,
              "y":228},
            "size":{
              "width":56,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fca3077496094256867816b18cb695ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"11px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":754,
                  "y":228},
                "size":{
                  "width":56,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"14f3cd8597874545bd5f23e3fb549613",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":665,
              "y":249},
            "size":{
              "width":142,
              "height":10},
            "borderWidth":"3"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/data/u60_line.png"}},
{
          "id":"6ce09b9c0de44306b94382780bb88766",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":266},
            "size":{
              "width":66,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"286ae4cf922042898829197482b1d266",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":266},
                "size":{
                  "width":66,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8dfcf451a28a4a2f8f06aacbc4cc6688",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":670,
              "y":285},
            "size":{
              "width":66,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c6e40ce69cc4b7b85056325ea432563",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":670,
                  "y":285},
                "size":{
                  "width":66,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1df597eb0bb34c4da1d35ba480258c74",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontSize":"11px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":670,
              "y":307},
            "size":{
              "width":96,
              "height":11}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61b93e973cc7413bbcc5ed40879149b5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontSize":"11px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":670,
                  "y":307},
                "size":{
                  "width":96,
                  "height":11}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"74cc465cde5f438b95bf80eebf08adcd",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFC9C9C9,
              "opacity":1},
            "location":{
              "x":323,
              "y":155},
            "size":{
              "width":48,
              "height":23}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4a3568b12cd4d27826aa9a2995a6dc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFC9C9C9,
                  "opacity":1},
                "location":{
                  "x":323,
                  "y":155},
                "size":{
                  "width":48,
                  "height":23}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5481accde4274eeb8373991c195a8eec",
          "label":"",
          "type":"treeNodeObject",
          "styleType":"treeNodeObject",
          "visible":true,
          "style":{
            "location":{
              "x":35,
              "y":234},
            "size":{
              "width":91,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"35089f627a7642348c07365eadd8b3d4",
              "label":"",
              "type":"treeNodeObject",
              "styleType":"treeNodeObject",
              "visible":true,
              "style":{
                "size":{
                  "width":91,
                  "height":20}},
              "adaptiveStyles":{
},
              "objects":[{
                  "id":"ea55a681fa8a46e8af06597546f54153",
                  "label":"",
                  "isContained":true,
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":91,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"9f9e58ba38f742e48c9788913eec946e",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":91,
                          "height":20}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}},
{
                  "id":"59c0989473284eb8ab0113b4a05fc77f",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":20},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"1518607358b94b239940e97890a62518",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":20},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"50924829f0c14cada4059335d570b7e0",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":20},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"1518607358b94b239940e97890a62518"},
{
                  "id":"2b97d8ef85254b0bbd256cd7ca5f68d3",
                  "label":"",
                  "type":"imageBox",
                  "styleType":"imageBox",
                  "visible":true,
                  "style":{
                    "stateStyles":{
                      "selected":{
}},
                    "location":{
                      "x":6,
                      "y":6},
                    "size":{
                      "width":9,
                      "height":9}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"226fe558303d49a485b63c484dfc9c42",
                      "label":"",
                      "isContained":true,
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "stateStyles":{
                          "selected":{
}},
                        "location":{
                          "x":6,
                          "y":6},
                        "size":{
                          "width":9,
                          "height":9}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/data/u33.png",
                    "selected~":"images/data/u33_selected.png"}},
{
                  "id":"0a7c0641163b4e8db532da59a86a2879",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":40},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"8df7a69d61534fbbae7609969147dc1f",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":40},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"758a39e20536468c8611d7f21bde852a",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":40},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"8df7a69d61534fbbae7609969147dc1f"},
{
                  "id":"e82712ba74de4a8caa1368e2149a3e69",
                  "label":"",
                  "type":"treeNodeObject",
                  "styleType":"treeNodeObject",
                  "visible":true,
                  "style":{
                    "location":{
                      "x":20,
                      "y":60},
                    "size":{
                      "width":76,
                      "height":20}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"bbbf1e56b523449fb4126ddbb19e79bf",
                      "label":"",
                      "isContained":true,
                      "type":"buttonShape",
                      "styleType":"buttonShape",
                      "visible":true,
                      "style":{
                        "location":{
                          "x":20,
                          "y":60},
                        "size":{
                          "width":76,
                          "height":20}},
                      "adaptiveStyles":{
},
                      "objects":[{
                          "id":"e25ec9f0240144bf816e82e924619052",
                          "label":"",
                          "isContained":true,
                          "type":"richTextPanel",
                          "styleType":"paragraph",
                          "visible":true,
                          "style":{
                            "location":{
                              "x":20,
                              "y":60},
                            "size":{
                              "width":76,
                              "height":20}},
                          "adaptiveStyles":{
}}],
                      "images":{
                        "normal~":"resources/images/transparent.gif"}}],
                  "buttonShapeId":"bbbf1e56b523449fb4126ddbb19e79bf"}],
              "buttonShapeId":"ea55a681fa8a46e8af06597546f54153"}]},
{
          "id":"d244cb2a48e6427da593d13550e84fdd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFFCC},
            "location":{
              "x":180,
              "y":189},
            "size":{
              "width":471,
              "height":28},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFCC33},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7e1d5a299de5416ea97b44eb3996143c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFFCC},
                "location":{
                  "x":180,
                  "y":189},
                "size":{
                  "width":471,
                  "height":28},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFCC33},
                "linePattern":"dashed"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u91.png"}},
{
          "id":"3b888d4dad8748c0a6db13ac0dc7bb5d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":238},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6499ebbcfaf04aca8a42d9a9aa045a49",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":238},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"429dca5808034cafbd0c21f3676f48ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":267,
              "y":237},
            "size":{
              "width":227,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1e39a5311c314e8b903587e21e6faabd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":267,
                  "y":237},
                "size":{
                  "width":227,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"23cf4bfad88949ab8d60cf6f5b9b4b2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":267,
              "y":308},
            "size":{
              "width":291,
              "height":31},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"422b314e97054ce18cfa4412a72d489a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":267,
                  "y":308},
                "size":{
                  "width":291,
                  "height":31},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u97.png"}},
{
          "id":"e67243eba08441e9bd29616118c9967f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":294},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e004c04730c94f33bc3f5b0eaa10ab43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":294},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c654bb6104444fab923542c4f488c7cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":267,
              "y":293},
            "size":{
              "width":227,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f75ec6fa9b3845b3a154d6e43c52ffd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":267,
                  "y":293},
                "size":{
                  "width":227,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19462fdfabff4cf89111fbe8b9f490af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":267,
              "y":364},
            "size":{
              "width":291,
              "height":31},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFFF2F2F2}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c40440bb9c743f48432fe21cac72c88",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":267,
                  "y":364},
                "size":{
                  "width":291,
                  "height":31},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFF2F2F2}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/data/u97.png"}},
{
          "id":"36ae7d8660894458b0bb4e41c03372da",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":180,
              "y":350},
            "size":{
              "width":65,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c455a7251844d47b75c09fa5065ea4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":180,
                  "y":350},
                "size":{
                  "width":65,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96dfeee4794542d3b635cae33044e1b0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "underline":true,
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF3399FF,
              "opacity":1},
            "location":{
              "x":267,
              "y":349},
            "size":{
              "width":227,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f1a2b85c93a4e8cae44152fc3926e68",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "underline":true,
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF3399FF,
                  "opacity":1},
                "location":{
                  "x":267,
                  "y":349},
                "size":{
                  "width":227,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30cdcc2e55e64bf78fd4696725e565cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Heiti SC Light', 'Heiti SC'",
            "fontWeight":"200",
            "location":{
              "x":192,
              "y":196},
            "size":{
              "width":53,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90485c88fe44489aa564e835bab3b4b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Heiti SC Light', 'Heiti SC'",
                "fontWeight":"200",
                "location":{
                  "x":192,
                  "y":196},
                "size":{
                  "width":53,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "b3c9a10d914b42c9984bba0666705c84":{
      "scriptId":"u0"},
    "cce1fd2bdd5a4d5cb87a65afbc9035fe":{
      "scriptId":"u1"},
    "65f156d8000549a98ce69eb4687fca9e":{
      "scriptId":"u2"},
    "3095da263ad5475490cb17589ec6e6ec":{
      "scriptId":"u3"},
    "33aeb46a84254423b22006fdf47d0d2b":{
      "scriptId":"u4"},
    "d5ff912f7387491ab2b9864abaa4870e":{
      "scriptId":"u5"},
    "fd94fc126d1e45bd845d48e39077b2ed":{
      "scriptId":"u6"},
    "17aae3e87d7b4a5995ba3c02354c549c":{
      "scriptId":"u7"},
    "934ba43265224f5a9ec9adf4a9cfaaaa":{
      "scriptId":"u8"},
    "619a959c1cf14d6a928f45ad33bb49af":{
      "scriptId":"u9"},
    "ef5fb7bb5c5e4b52bc01a736a91459c6":{
      "scriptId":"u10"},
    "6513471d99cd4cc0899cefae7cafa482":{
      "scriptId":"u11"},
    "441de1f5b4da46478441b1b40a4b6e40":{
      "scriptId":"u12"},
    "5fb50c224c5840c0b8e01ff8e1dd2e2d":{
      "scriptId":"u13"},
    "e24ed4c2b1c34b009af632db32374d7a":{
      "scriptId":"u14"},
    "014247a9283e410ea1d918aeadef7c5a":{
      "scriptId":"u15"},
    "68e98ab38fb2409f9c56c4e819e47e41":{
      "scriptId":"u16"},
    "d93ca05f077b422b963accec2e5c87ac":{
      "scriptId":"u17"},
    "baf530ac4ad84eaa9e276fe0b652631c":{
      "scriptId":"u18"},
    "64f9351d97a349d893bc95f8131586e2":{
      "scriptId":"u19"},
    "5018abc3292f4eacaff60a3a5959f3e0":{
      "scriptId":"u20"},
    "98a5d42254904453b87e68cec138336a":{
      "scriptId":"u21"},
    "d6ef87978af14869adf628da8bd570e7":{
      "scriptId":"u22"},
    "058bb836951d4167ba56127c9dc8982a":{
      "scriptId":"u23"},
    "6c976049024246ff94aba834232d5954":{
      "scriptId":"u24"},
    "4a249a8f59224c3ca0448de0fe4a1e9b":{
      "scriptId":"u25"},
    "96d1a76fc861434583828145b99fb12f":{
      "scriptId":"u26"},
    "eb1ed36a7dd34f25937b902b5d3d95d6":{
      "scriptId":"u27"},
    "b883eb5b4017425387460a4bdba67b40":{
      "scriptId":"u28"},
    "5bb4ed51fbea4c5294e4802547ebd4e6":{
      "scriptId":"u29"},
    "6bd60adaccbb4a2b8a581ab7f01ad00c":{
      "scriptId":"u30"},
    "349aecee344447f9b37f4ccf432009c3":{
      "scriptId":"u31"},
    "71b738eaef444753bb4ea490fcfff660":{
      "scriptId":"u32"},
    "ead7117a07df4246b2be4e035d387888":{
      "scriptId":"u33"},
    "fc111f3f00504153aaad924bfb800f8c":{
      "scriptId":"u34"},
    "ff2ad1ab7fe8408f8992be5269e2e6da":{
      "scriptId":"u35"},
    "9169b47aff924eb9a7edb56d89277bcb":{
      "scriptId":"u36"},
    "f1544718c97245f3a3ddaae1caa42216":{
      "scriptId":"u37"},
    "c56e3f862a6d45a7aedfc74c2976f7fa":{
      "scriptId":"u38"},
    "cf84650e84a946e08fd8885e88dee3a2":{
      "scriptId":"u39"},
    "65558c793c5643a18e4328caf87d9cf2":{
      "scriptId":"u40"},
    "550c9befc02248379045e016e9269739":{
      "scriptId":"u41"},
    "bfa155ffaa514e6ead0719e5c3bbbc44":{
      "scriptId":"u42"},
    "7db9b1c9f9b5472fbeee30343e5fbcf0":{
      "scriptId":"u43"},
    "bbca3ed6511145c7afb2e9876c5fbf7d":{
      "scriptId":"u44"},
    "a97d79ab46a642acbe95dfa3c267b19d":{
      "scriptId":"u45"},
    "5ce4a9a3026a4455aada90d2a0e36fab":{
      "scriptId":"u46"},
    "f87c9ffa6c8143cbb60f883eec07a960":{
      "scriptId":"u47"},
    "9575aa3ef5cb41c680ab7097cedd6297":{
      "scriptId":"u48"},
    "451e9afc934e4fda97cba86ba3557ebb":{
      "scriptId":"u49"},
    "c238e466333548069279d2cb9e181e89":{
      "scriptId":"u50"},
    "0e742a48d67f47188fe7f0d6733dc673":{
      "scriptId":"u51"},
    "6d7d2cd6bcba4f728159aea00ed148d6":{
      "scriptId":"u52"},
    "2936c58512e74bbebb9dc648d17c9c0d":{
      "scriptId":"u53"},
    "9afb30d13a8e4b888ae645d4a22412dd":{
      "scriptId":"u54"},
    "761362c8cc5f44468dada9fa654fe68a":{
      "scriptId":"u55"},
    "63ecaea79c444ccc91de1b7dddfa676a":{
      "scriptId":"u56"},
    "2d12b69e7b704426ab8199f855f3ff1a":{
      "scriptId":"u57"},
    "ffb052063f134553afd30638bfc46b3e":{
      "scriptId":"u58"},
    "9ce680f519fc4a74a264c187aeb4e3ac":{
      "scriptId":"u59"},
    "80625e432e8f46009c06da32bef3c45b":{
      "scriptId":"u60"},
    "886c9cd9284f43c4a07bb6918e33e1b5":{
      "scriptId":"u61"},
    "3f8462fd52664d1eaa5d042544a24ce3":{
      "scriptId":"u62"},
    "3a1ac012e7934734955b02afa5b7417d":{
      "scriptId":"u63"},
    "588422fa02b54feca85e41e2262de3ed":{
      "scriptId":"u64"},
    "da277a58fcae4372a3cd2a158cb33f96":{
      "scriptId":"u65"},
    "fca3077496094256867816b18cb695ee":{
      "scriptId":"u66"},
    "14f3cd8597874545bd5f23e3fb549613":{
      "scriptId":"u67"},
    "6ce09b9c0de44306b94382780bb88766":{
      "scriptId":"u68"},
    "286ae4cf922042898829197482b1d266":{
      "scriptId":"u69"},
    "8dfcf451a28a4a2f8f06aacbc4cc6688":{
      "scriptId":"u70"},
    "0c6e40ce69cc4b7b85056325ea432563":{
      "scriptId":"u71"},
    "1df597eb0bb34c4da1d35ba480258c74":{
      "scriptId":"u72"},
    "61b93e973cc7413bbcc5ed40879149b5":{
      "scriptId":"u73"},
    "74cc465cde5f438b95bf80eebf08adcd":{
      "scriptId":"u74"},
    "b4a3568b12cd4d27826aa9a2995a6dc6":{
      "scriptId":"u75"},
    "5481accde4274eeb8373991c195a8eec":{
      "scriptId":"u76"},
    "35089f627a7642348c07365eadd8b3d4":{
      "scriptId":"u77"},
    "2b97d8ef85254b0bbd256cd7ca5f68d3":{
      "scriptId":"u78"},
    "226fe558303d49a485b63c484dfc9c42":{
      "scriptId":"u79"},
    "ea55a681fa8a46e8af06597546f54153":{
      "scriptId":"u80"},
    "9f9e58ba38f742e48c9788913eec946e":{
      "scriptId":"u81"},
    "59c0989473284eb8ab0113b4a05fc77f":{
      "scriptId":"u82"},
    "1518607358b94b239940e97890a62518":{
      "scriptId":"u83"},
    "50924829f0c14cada4059335d570b7e0":{
      "scriptId":"u84"},
    "0a7c0641163b4e8db532da59a86a2879":{
      "scriptId":"u85"},
    "8df7a69d61534fbbae7609969147dc1f":{
      "scriptId":"u86"},
    "758a39e20536468c8611d7f21bde852a":{
      "scriptId":"u87"},
    "e82712ba74de4a8caa1368e2149a3e69":{
      "scriptId":"u88"},
    "bbbf1e56b523449fb4126ddbb19e79bf":{
      "scriptId":"u89"},
    "e25ec9f0240144bf816e82e924619052":{
      "scriptId":"u90"},
    "d244cb2a48e6427da593d13550e84fdd":{
      "scriptId":"u91"},
    "7e1d5a299de5416ea97b44eb3996143c":{
      "scriptId":"u92"},
    "3b888d4dad8748c0a6db13ac0dc7bb5d":{
      "scriptId":"u93"},
    "6499ebbcfaf04aca8a42d9a9aa045a49":{
      "scriptId":"u94"},
    "429dca5808034cafbd0c21f3676f48ca":{
      "scriptId":"u95"},
    "1e39a5311c314e8b903587e21e6faabd":{
      "scriptId":"u96"},
    "23cf4bfad88949ab8d60cf6f5b9b4b2d":{
      "scriptId":"u97"},
    "422b314e97054ce18cfa4412a72d489a":{
      "scriptId":"u98"},
    "e67243eba08441e9bd29616118c9967f":{
      "scriptId":"u99"},
    "e004c04730c94f33bc3f5b0eaa10ab43":{
      "scriptId":"u100"},
    "c654bb6104444fab923542c4f488c7cc":{
      "scriptId":"u101"},
    "f75ec6fa9b3845b3a154d6e43c52ffd9":{
      "scriptId":"u102"},
    "19462fdfabff4cf89111fbe8b9f490af":{
      "scriptId":"u103"},
    "5c40440bb9c743f48432fe21cac72c88":{
      "scriptId":"u104"},
    "36ae7d8660894458b0bb4e41c03372da":{
      "scriptId":"u105"},
    "3c455a7251844d47b75c09fa5065ea4e":{
      "scriptId":"u106"},
    "96dfeee4794542d3b635cae33044e1b0":{
      "scriptId":"u107"},
    "2f1a2b85c93a4e8cae44152fc3926e68":{
      "scriptId":"u108"},
    "30cdcc2e55e64bf78fd4696725e565cb":{
      "scriptId":"u109"},
    "90485c88fe44489aa564e835bab3b4b8":{
      "scriptId":"u110"}}});